#1) 
fav_animes = ['tokio ghoul', 'demon slayer', 'black buttle', 'mha', 'jujutsu caisen', 'naruto', 'berserk']
print(fav_animes)
#2)
foods = ['ხინკალი', 'ღომი', 'შაურმა', 'ლობიანი', 'ხაჭაპური', 'ქათმის ხორცი ტყემალთან უუჯჰ', 'ორაგული', 'ვინეგრეტი','გაჩეჩილი', 'პიურე კატლეტთან უჰჰჰჰჰჰჰ']
print(foods)
#3)
num = [1,  2,  3,   4,  5,  6,  7,   8,  9,  10]
print(num[1:7])
print(num[4:9])
print(num[0])
print(num[1])
print(num[2])
print(num[3])
print(num[4])
print(num[5])
print(num[6])
print(num[7])
print(num[8])
print(num[9])